#!/usr/bin/env bash
# Clone and pin the official upstream repos for Phase A (F2/F3/F4).
# Never edit these checkouts in place - see README "Do not edit upstream".
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p third_party

clone_pin () {
    local url="$1" dir="$2"
    if [ -d "third_party/$dir/.git" ]; then
        echo "[setup_third_party] $dir already cloned, skipping"
    else
        git clone "$url" "third_party/$dir"
    fi
}

# F2 (ENGLISH-RANDOM) + F3 (Perinucleus): same upstream repo/paper.
clone_pin "https://github.com/SewoongLab/scalable-fingerprinting-of-llms.git" "scalable_fp"

# F4 (CTCC): datasets + LoRA-merge/eval helper scripts. Training itself runs
# through LLaMA-Factory, which the repo's own README depends on (it ships no
# training code of its own).
clone_pin "https://github.com/Xuzhenhua55/CTCC.git" "ctcc"

# CTCC's documented training/inference engine.
clone_pin "https://github.com/hiyouga/LLaMA-Factory.git" "llama_factory"

{
    echo "# Upstream revisions (Phase A: F2/F3/F4)"
    echo
    echo "Regenerated by scripts/setup_third_party.sh — do not hand-edit commit hashes."
    echo
    for dir in scalable_fp ctcc llama_factory; do
        commit=$(git -C "third_party/$dir" rev-parse HEAD)
        url=$(git -C "third_party/$dir" remote get-url origin)
        echo "- $dir"
        echo "  - repo: $url"
        echo "  - commit: \`$commit\`"
        echo
    done
} > third_party/UPSTREAM_VERSIONS.md

cat third_party/UPSTREAM_VERSIONS.md
echo "[setup_third_party] pinned revisions written to third_party/UPSTREAM_VERSIONS.md"
