#!/usr/bin/env bash
# Clone and pin the official upstream repos for Phase A (F2/F3/F4).
# Never edit these checkouts in place - see README "Do not edit upstream".
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p third_party

clone_pin () {
    local url="$1" dir="$2"
    if [ -d "third_party/$dir/.git" ]; then
        echo "[setup_third_party] $dir already cloned, skipping"
    else
        git clone "$url" "third_party/$dir"
    fi
}

# F2 (ENGLISH-RANDOM) + F3 (Perinucleus): same upstream repo/paper.
clone_pin "https://github.com/SewoongLab/scalable-fingerprinting-of-llms.git" "scalable_fp"

# Minimal documented compatibility patch (found running against real weights on
# an A100 box): generate_finetuning_data.py's `key_response_strategy=independent`
# path calls `pipeline(text, max_length=N, ...)` where N is meant as a "how many
# new tokens" budget, but a newer transformers (5.x) validates `max_length` as a
# TOTAL sequence length cap and hard-errors as soon as the tokenized input alone
# already reaches N (ValueError: "Input length of input_ids is N, but
# `max_length` is set to N ... consider setting `max_new_tokens`" - literally the
# library's own suggested fix). This never surfaced against the repo's own pinned
# transformers==4.44.2, which validated this loosely. Swapping max_length->
# max_new_tokens for these 4 call sites preserves the exact same intent (N new
# tokens for the key/response) and fixes it for any transformers version.
if [ -d "third_party/scalable_fp/.git" ] && ! grep -q "max_new_tokens=key_length" "third_party/scalable_fp/generate_finetuning_data.py"; then
    echo "[setup_third_party] applying scalable_fp_max_new_tokens.patch"
    git -C third_party/scalable_fp apply "$ROOT/third_party/patches/scalable_fp_max_new_tokens.patch"
fi

# F4 (CTCC): datasets + LoRA-merge/eval helper scripts. Training itself runs
# through LLaMA-Factory, which the repo's own README depends on (it ships no
# training code of its own).
clone_pin "https://github.com/Xuzhenhua55/CTCC.git" "ctcc"

# CTCC's documented training/inference engine.
clone_pin "https://github.com/hiyouga/LLaMA-Factory.git" "llama_factory"

{
    echo "# Upstream revisions (Phase A: F2/F3/F4)"
    echo
    echo "Regenerated by scripts/setup_third_party.sh — do not hand-edit commit hashes."
    echo
    for dir in scalable_fp ctcc llama_factory; do
        commit=$(git -C "third_party/$dir" rev-parse HEAD)
        url=$(git -C "third_party/$dir" remote get-url origin)
        echo "- $dir"
        echo "  - repo: $url"
        echo "  - commit: \`$commit\`"
        echo
    done
} > third_party/UPSTREAM_VERSIONS.md

cat third_party/UPSTREAM_VERSIONS.md
echo "[setup_third_party] pinned revisions written to third_party/UPSTREAM_VERSIONS.md"
